--UsaMedicamentos
ALTER TABLE USAMEDICAMENTOS DROP CONSTRAINT FK_UsaMedicamentos_HistorialesClinicos;
ALTER TABLE USAMEDICAMENTOS ADD CONSTRAINT FK_UsaMedicamentos_HistorialesClinicos
    FOREIGN KEY (historialClinico) REFERENCES HISTORIALESCLINICOS(registro)
        ON DELETE CASCADE;
        
--Empleados
ALTER TABLE USAMEDICAMENTOS DROP CONSTRAINT FK_USAMEDICAMENTOS_EMPLEADOS;
ALTER TABLE USAMEDICAMENTOS ADD CONSTRAINT FK_USAMEDICAMENTOS_EMPLEADOS
    FOREIGN KEY (empleado) REFERENCES EMPLEADOS(id)
        ON DELETE SET NULL;

--Profesionales
ALTER TABLE FERTILIDADES DROP CONSTRAINT FK_FERTILIDADES_PROFESIONALES;
ALTER TABLE FERTILIDADES ADD CONSTRAINT FK_FERTILIDADES_PROFESIONALES
    FOREIGN KEY (veterinario) REFERENCES PROFESIONALES(id)
        ON DELETE SET NULL;
        
ALTER TABLE HISTORIALESCLINICOS DROP CONSTRAINT FK_HistorialesClinicos_Profesionales;
ALTER TABLE HISTORIALESCLINICOS ADD CONSTRAINT FK_HistorialesClinicos_Profesionales
    FOREIGN KEY (profesional) REFERENCES PROFESIONALES(id)
        ON DELETE SET NULL;
