/*FK*/

ALTER TABLE ANIMALES ADD CONSTRAINT FK_Animales_Ganaderos
    FOREIGN KEY (propietario) REFERENCES GANADEROS(id);
ALTER TABLE ANIMALES ADD CONSTRAINT FK_Animales_Compras
    FOREIGN KEY (compra) REFERENCES COMPRAS(idCompra);
ALTER TABLE ANIMALES ADD CONSTRAINT FK_Animales_Ventas
    FOREIGN KEY (venta) REFERENCES VENTAS(idVenta);
ALTER TABLE ANIMALES ADD CONSTRAINT FK_Animales_Partos
    FOREIGN KEY (parto) REFERENCES PARTOS(id);   
ALTER TABLE PADRES ADD CONSTRAINT FK_Padres1_Animales
    FOREIGN KEY (animal1, propietario1) REFERENCES ANIMALES(id, propietario);
ALTER TABLE PADRES ADD CONSTRAINT FK_Padres2_Animales
    FOREIGN KEY (animal2, propietario2) REFERENCES ANIMALES(id, propietario);   
ALTER TABLE COMPRAS ADD CONSTRAINT FK_Compras_Ganaderos
    FOREIGN KEY (comprador) REFERENCES GANADEROS(id);
ALTER TABLE VENTAS ADD CONSTRAINT FK_Ventas_Ganaderos
    FOREIGN KEY (vendedor) REFERENCES GANADEROS(id);    
ALTER TABLE HEMBRASACTIVAS ADD CONSTRAINT FK_HembrasActivas_Animales
    FOREIGN KEY (animal, propietarioAnimal) REFERENCES ANIMALES(id, propietario);
ALTER TABLE MACHOSACTIVOS ADD CONSTRAINT FK_MachosActivos_Animales
    FOREIGN KEY (animal, propietarioAnimal) REFERENCES ANIMALES(id, propietario);
ALTER TABLE MUERTES ADD CONSTRAINT FK_Muertes_Animales
    FOREIGN KEY (animal, propietarioAnimal) REFERENCES ANIMALES(id,propietario);  
ALTER TABLE FERTILIDADES ADD CONSTRAINT FK_Fertilidades_HembrasActivas
    FOREIGN KEY (hembraActiva, propietarioHembraActiva) REFERENCES HEMBRASACTIVAS(animal, propietarioAnimal);
ALTER TABLE FERTILIDADES ADD CONSTRAINT FK_Fertilidades_Profesionales
    FOREIGN KEY (veterinario) REFERENCES PROFESIONALES(id);   
ALTER TABLE PARTOS ADD CONSTRAINT FK_Partos_HembrasActivas
    FOREIGN KEY (hembraActiva, propietarioHembraActiva) REFERENCES HEMBRASACTIVAS(animal, propietarioAnimal);
ALTER TABLE PARTOS ADD CONSTRAINT FK_Partos_FertilidadesCofirmadas
    FOREIGN KEY (fertilidadConfirmada) REFERENCES FERTILIDADESCONFIRMADAS(fertilidad);
ALTER TABLE HISTORIALESCLINICOS ADD CONSTRAINT FK_HistorialesClinicos_Animales
    FOREIGN KEY (animal, propietarioanimal) REFERENCES ANIMALES(id, propietario);
ALTER TABLE HISTORIALESCLINICOS ADD CONSTRAINT FK_HistorialesClinicos_Profesionales
    FOREIGN KEY (profesional) REFERENCES PROFESIONALES(id);    
ALTER TABLE USAMEDICAMENTOS ADD CONSTRAINT FK_UsaMedicamentos_Medicamentos 
    FOREIGN KEY (medicamento) REFERENCES MEDICAMENTOS(id);
ALTER TABLE USAMEDICAMENTOS ADD CONSTRAINT FK_UsaMedicamentos_HistorialesClinicos
    FOREIGN KEY (historialClinico) REFERENCES HISTORIALESCLINICOS(registro);
ALTER TABLE USAMEDICAMENTOS ADD CONSTRAINT FK_UsaMedicamentos_Empleados
    FOREIGN KEY (empleado) REFERENCES EMPLEADOS(id);     
ALTER TABLE CASTRACIONES ADD CONSTRAINT FK_Castraciones_Animales
    FOREIGN KEY (animal, propietarioAnimal) REFERENCES ANIMALES(id, propietario);
ALTER TABLE HERRAJESESPECIALES ADD CONSTRAINT FK_HerrajesEspeciales_Animales
    FOREIGN KEY (animal, propietarioAnimal) REFERENCES ANIMALES(id, propietario);
ALTER TABLE FERTILIDADESCONFIRMADAS ADD CONSTRAINT FK_FertilidadesCofirmadas_Fertilidades
    FOREIGN KEY (fertilidad) REFERENCES FERTILIDADES(id);
ALTER TABLE FERTILIDADESCONFIRMADAS ADD CONSTRAINT FK_FertilidadesCofirmadas_MachosActivos
    FOREIGN KEY (machoActivo, propietarioMachoActivo) REFERENCES MACHOSACTIVOS(animal, propietarioAnimal);
    
--Secuencias
CREATE SEQUENCE GANADEROS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEDICAMENTOS_SEQ START WITH 1 INCREMENT BY 1;