ALTER TABLE GANADEROS ADD CONSTRAINT UK_GANADEROS UNIQUE(CLAVE);

ALTER TABLE PROFESIONALES ADD CONSTRAINT UK_PROFESIONALES UNIQUE(NOTPROFESIONAL, PROFESION);

ALTER TABLE EMPLEADOS ADD CONSTRAINT UK_EMPLEADOS UNIQUE(NODOCUMENTO, TIPODOCUMENTO);

ALTER TABLE CASTRACIONES ADD CONSTRAINT UK_CASTRACIONES UNIQUE(ANIMAL, PROPIETARIOANIMAL);

ALTER TABLE MUERTES ADD CONSTRAINT UK_MUERTES UNIQUE(ANIMAL, PROPIETARIOANIMAL);