-- ANIMALES
ALTER TABLE ANIMALES DROP CONSTRAINT FK_ANIMALES_GANADEROS;

ALTER TABLE ANIMALES DROP CONSTRAINT FK_ANIMALES_COMPRAS;

ALTER TABLE ANIMALES DROP CONSTRAINT FK_ANIMALES_VENTAS;

ALTER TABLE ANIMALES DROP CONSTRAINT FK_ANIMALES_PARTOS;

-- PADRES
ALTER TABLE PADRES DROP CONSTRAINT FK_PADRES1_ANIMALES;

ALTER TABLE PADRES DROP CONSTRAINT FK_PADRES2_ANIMALES;

-- COMPRAS y VENTAS
ALTER TABLE COMPRAS DROP CONSTRAINT FK_COMPRAS_GANADEROS;

ALTER TABLE VENTAS DROP CONSTRAINT FK_VENTAS_GANADEROS;

-- HEMBRASACTIVAS y MACHOSACTIVOS
ALTER TABLE HEMBRASACTIVAS DROP CONSTRAINT FK_HEMBRASACTIVAS_ANIMALES;

ALTER TABLE MACHOSACTIVOS DROP CONSTRAINT FK_MACHOSACTIVOS_ANIMALES;

-- MUERTES
ALTER TABLE MUERTES DROP CONSTRAINT FK_MUERTES_ANIMALES;

-- FERTILIDADES
ALTER TABLE FERTILIDADES DROP CONSTRAINT FK_FERTILIDADES_HEMBRASACTIVAS;

ALTER TABLE FERTILIDADES DROP CONSTRAINT FK_FERTILIDADES_PROFESIONALES;

-- PARTOS
ALTER TABLE PARTOS DROP CONSTRAINT FK_PARTOS_HEMBRASACTIVAS;

ALTER TABLE PARTOS DROP CONSTRAINT FK_PARTOS_FERTILIDADESCOFIRMADAS;

-- HISTORIALESCLINICOS
ALTER TABLE HISTORIALESCLINICOS DROP CONSTRAINT FK_HISTORIALESCLINICOS_ANIMALES;

ALTER TABLE HISTORIALESCLINICOS DROP CONSTRAINT FK_HISTORIALESCLINICOS_PROFESIONALES;

-- USAMEDICAMENTOS
ALTER TABLE USAMEDICAMENTOS DROP CONSTRAINT FK_USAMEDICAMENTOS_MEDICAMENTOS;

ALTER TABLE USAMEDICAMENTOS DROP CONSTRAINT FK_USAMEDICAMENTOS_HISTORIALESCLINICOS;

ALTER TABLE USAMEDICAMENTOS DROP CONSTRAINT FK_USAMEDICAMENTOS_EMPLEADOS;

-- CASTRACIONES y HERRAJESESPECIALES
ALTER TABLE CASTRACIONES DROP CONSTRAINT FK_CASTRACIONES_ANIMALES;

ALTER TABLE HERRAJESESPECIALES DROP CONSTRAINT FK_HERRAJESESPECIALES_ANIMALES;

-- FERTILIDADESCONFIRMADAS
ALTER TABLE FERTILIDADESCONFIRMADAS DROP CONSTRAINT FK_FERTILIDADESCOFIRMADAS_FERTILIDADES;

ALTER TABLE FERTILIDADESCONFIRMADAS DROP CONSTRAINT FK_FERTILIDADESCOFIRMADAS_MACHOSACTIVOS;



TRUNCATE TABLE ANIMALES;

TRUNCATE TABLE GANADEROS;

TRUNCATE TABLE PADRES;

TRUNCATE TABLE COMPRAS;

TRUNCATE TABLE VENTAS;

TRUNCATE TABLE HEMBRASACTIVAS;

TRUNCATE TABLE MACHOSACTIVOS;

TRUNCATE TABLE MUERTES;

TRUNCATE TABLE CASTRACIONES;

TRUNCATE TABLE HERRAJESESPECIALES;

TRUNCATE TABLE PARTOS;

TRUNCATE TABLE FERTILIDADES;

TRUNCATE TABLE FERTILIDADESCONFIRMADAS;

TRUNCATE TABLE PROFESIONALES;

TRUNCATE TABLE EMPLEADOS;

TRUNCATE TABLE HISTORIALESCLINICOS;

TRUNCATE TABLE USAMEDICAMENTOS;

TRUNCATE TABLE MEDICAMENTOS;

DROP SEQUENCE GANADEROS_SEQ;

DROP SEQUENCE MEDICAMENTOS_SEQ;