REVOKE EXECUTE ON PA_SOCIOGANADERO FROM SOCIOGANADERO;
DROP ROLE SOCIOGANADERO;

REVOKE EXECUTE ON PA_DUEÑO FROM DUENIO;
DROP ROLE DUENIO;

REVOKE EXECUTE ON PA_ENCARGADO FROM ENCARGADO;
DROP ROLE ENCARGADO;

REVOKE EXECUTE ON PA_VETERINARIO FROM VETERINARIO;
DROP ROLE VETERINARIO;

DROP PACKAGE PA_SOCIOGANADERO;
DROP PACKAGE PA_DUENIO;
DROP PACKAGE PA_ENCARGADO;
DROP PACKAGE PA_VETERINARIO;
